// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5R7TpQN-gFylqGSSWVjxG-hHmpE6xTQk',
    appId: '1:205984747203:web:f7ff3cd5637d4d85955c76',
    messagingSenderId: '205984747203',
    projectId: 'car-park-booking-79af7',
    authDomain: 'car-park-booking-79af7.firebaseapp.com',
    storageBucket: 'car-park-booking-79af7.firebasestorage.app',
    measurementId: 'G-HVLJ8N5EW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTbps3HBJ3fst2ahi93yxgamfYMiKQotU',
    appId: '1:205984747203:android:04f13ce4b7d3a927955c76',
    messagingSenderId: '205984747203',
    projectId: 'car-park-booking-79af7',
    storageBucket: 'car-park-booking-79af7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-NaDrYC6SqrIYFtiBTa2Ogl1teuEckCg',
    appId: '1:205984747203:ios:c9b748557c1e6b20955c76',
    messagingSenderId: '205984747203',
    projectId: 'car-park-booking-79af7',
    storageBucket: 'car-park-booking-79af7.firebasestorage.app',
    iosBundleId: 'com.example.carParkBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-NaDrYC6SqrIYFtiBTa2Ogl1teuEckCg',
    appId: '1:205984747203:ios:c9b748557c1e6b20955c76',
    messagingSenderId: '205984747203',
    projectId: 'car-park-booking-79af7',
    storageBucket: 'car-park-booking-79af7.firebasestorage.app',
    iosBundleId: 'com.example.carParkBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5R7TpQN-gFylqGSSWVjxG-hHmpE6xTQk',
    appId: '1:205984747203:web:89a0a61d92178225955c76',
    messagingSenderId: '205984747203',
    projectId: 'car-park-booking-79af7',
    authDomain: 'car-park-booking-79af7.firebaseapp.com',
    storageBucket: 'car-park-booking-79af7.firebasestorage.app',
    measurementId: 'G-K290687D01',
  );
}
